// Seeded sample for the concierge outreach surface (#434 / #533).
// Stand-in for live /pitches so the board, builder and token flows are
// demoable and verifiable offline; replaced by live data when reachable.
//
// Every person, org and contact below is invented. Real targets only ever exist
// behind the live API — this file must never be used to park real contact details.

export const MOCK_PITCHES = [
  {
    pitch_id: 'pl_draft_nordic',
    target_name: 'Ava Lindqvist',
    target_org: 'Nordic Film Institute',
    target_contact: 'ava.lindqvist@example.org',
    source_url: 'https://example.org/nfi/ava-nordic-noir',
    source_attribution: 'Public staff-picks page, Nordic Film Institute',
    proposed_title: 'Essential Nordic Noir',
    proposed_description: 'Twenty-four films that built the genre, in the order Ava lists them.',
    thing_type: 'Movie',
    category: 'film',
    status: 'draft',
    can_repitch: false,
    invite_token: null,
    invite_expires_at: null,
    invite_used_at: null,
    preview_token: null,
    created_by: 'staff@listgem.com',
    assigned_to: 'staff@listgem.com',
    notes: 'Source page is stable, attribution line agreed with legal.',
    provisioned_list_id: null,
    provisioned_user_id: null,
    pitched_at: null,
    responded_at: null,
    provisioned_at: null,
    created_at: '2026-08-04T09:12:00Z',
    updated_at: '2026-08-08T15:40:00Z',
    item_count: 24,
    resolved_count: 21,
  },
  {
    pitch_id: 'pl_pitched_fork',
    target_name: 'Marcus Oyelaran',
    target_org: 'The Wandering Fork',
    target_contact: 'hello@example.com',
    source_url: 'https://example.com/wandering-fork/best-of-lagos',
    source_attribution: 'The Wandering Fork, “Best of Lagos” column',
    proposed_title: 'Best of Lagos: 30 Tables',
    proposed_description: null,
    thing_type: 'Restaurant',
    category: 'food',
    status: 'pitched',
    can_repitch: false,
    invite_token: null,
    invite_expires_at: null,
    invite_used_at: null,
    preview_token: 'pv_9f2c1d7a',
    created_by: 'staff@listgem.com',
    assigned_to: 'gtm@listgem.com',
    notes: 'Preview sent 2026-08-07. Follow up in a week if quiet.',
    provisioned_list_id: null,
    provisioned_user_id: null,
    pitched_at: '2026-08-07T11:02:00Z',
    responded_at: null,
    provisioned_at: null,
    created_at: '2026-08-02T14:20:00Z',
    updated_at: '2026-08-07T11:02:00Z',
    item_count: 30,
    resolved_count: 28,
  },
  {
    pitch_id: 'pl_accepted_reading',
    target_name: 'Priya Raghunathan',
    target_org: 'Ashfield College',
    target_contact: 'p.raghunathan@example.edu',
    source_url: 'https://example.edu/ashfield/syllabus/postcolonial-lit',
    source_attribution: 'Course syllabus, Ashfield College',
    proposed_title: 'Postcolonial Literature: The Reading List',
    proposed_description: 'The syllabus, unabridged.',
    thing_type: 'Book',
    category: 'books',
    status: 'accepted',
    can_repitch: false,
    invite_token: 'inv_4b81ce02',
    invite_expires_at: '2026-09-06T10:00:00Z',
    invite_used_at: null,
    preview_token: 'pv_31aa0c58',
    created_by: 'gtm@listgem.com',
    assigned_to: 'gtm@listgem.com',
    notes: 'Said yes by email 2026-08-09. Invite sent same day.',
    provisioned_list_id: null,
    provisioned_user_id: null,
    pitched_at: '2026-08-05T09:00:00Z',
    responded_at: '2026-08-09T16:30:00Z',
    provisioned_at: null,
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-09T16:35:00Z',
    item_count: 18,
    resolved_count: 18,
  },
  {
    pitch_id: 'pl_provisioned_tv',
    target_name: 'Tomás Beltrán',
    target_org: null,
    target_contact: 'tomas@example.net',
    source_url: 'https://example.net/tomas/serials',
    source_attribution: 'Personal site, “Serials I keep rewatching”',
    proposed_title: 'Serials I Keep Rewatching',
    proposed_description: null,
    thing_type: 'TVSeries',
    category: 'tv',
    status: 'provisioned',
    can_repitch: false,
    invite_token: 'inv_7d3390fa',
    invite_expires_at: '2026-09-01T10:00:00Z',
    invite_used_at: '2026-08-10T08:14:00Z',
    preview_token: 'pv_5c77e1b3',
    created_by: 'gtm@listgem.com',
    assigned_to: 'gtm@listgem.com',
    notes: 'Claimed the draft the morning after the invite went out.',
    provisioned_list_id: 'list_84c1',
    provisioned_user_id: 'usr_2f19bc',
    pitched_at: '2026-07-30T09:00:00Z',
    responded_at: '2026-08-08T12:00:00Z',
    provisioned_at: '2026-08-10T08:14:00Z',
    created_at: '2026-07-28T13:45:00Z',
    updated_at: '2026-08-10T08:14:00Z',
    item_count: 12,
    resolved_count: 12,
  },
  {
    pitch_id: 'pl_quiet_kobayashi',
    target_name: 'Hana Kobayashi',
    target_org: 'Setouchi Design Review',
    target_contact: 'editor@example.jp',
    source_url: 'https://example.jp/sdr/museums',
    source_attribution: 'Setouchi Design Review, museum guide',
    proposed_title: 'Island Museums of the Inland Sea',
    proposed_description: null,
    thing_type: 'Museum',
    category: 'places',
    status: 'no_response',
    can_repitch: true,
    invite_token: null,
    invite_expires_at: null,
    invite_used_at: null,
    preview_token: 'pv_0ab4f612',
    created_by: 'staff@listgem.com',
    assigned_to: 'staff@listgem.com',
    notes: 'No reply after two weeks. Worth one more try in September.',
    provisioned_list_id: null,
    provisioned_user_id: null,
    pitched_at: '2026-07-22T10:15:00Z',
    responded_at: null,
    provisioned_at: null,
    created_at: '2026-07-20T09:30:00Z',
    updated_at: '2026-08-06T09:00:00Z',
    item_count: 15,
    resolved_count: 11,
  },
  {
    pitch_id: 'pl_declined_adeyemi',
    target_name: 'Whitney Adeyemi-Cole',
    target_org: null,
    target_contact: 'w.adeyemi.cole@example.com',
    source_url: 'https://example.com/whitney/records-of-the-year',
    source_attribution: 'Personal blog, year-end records post',
    proposed_title: 'Records of the Year',
    proposed_description: null,
    thing_type: 'MusicAlbum',
    category: 'music',
    status: 'declined',
    can_repitch: false,
    invite_token: null,
    invite_expires_at: null,
    invite_used_at: null,
    preview_token: null,
    created_by: 'gtm@listgem.com',
    assigned_to: 'gtm@listgem.com',
    notes: 'Explicit no — asked not to be contacted about this again.',
    provisioned_list_id: null,
    provisioned_user_id: null,
    pitched_at: '2026-07-15T11:00:00Z',
    responded_at: '2026-07-16T18:20:00Z',
    provisioned_at: null,
    created_at: '2026-07-14T16:00:00Z',
    updated_at: '2026-07-16T18:20:00Z',
    item_count: 20,
    resolved_count: 19,
  },
  {
    pitch_id: 'pl_archived_sandoval',
    target_name: 'Rafael Sandoval',
    target_org: 'Cordillera Trails',
    target_contact: null, // purged by takedown
    source_url: 'https://example.org/cordillera/high-routes',
    source_attribution: 'Cordillera Trails, high-route index',
    proposed_title: 'High Routes of the Cordillera',
    proposed_description: null,
    thing_type: 'Park',
    category: 'places',
    status: 'archived',
    can_repitch: false,
    invite_token: null,
    invite_expires_at: null,
    invite_used_at: null,
    preview_token: null,
    created_by: 'staff@listgem.com',
    assigned_to: null,
    notes: 'Takedown requested by the source site. Contact purged, tokens revoked.',
    provisioned_list_id: null,
    provisioned_user_id: null,
    pitched_at: '2026-06-30T10:00:00Z',
    responded_at: null,
    provisioned_at: null,
    created_at: '2026-06-28T12:00:00Z',
    updated_at: '2026-07-11T09:05:00Z',
    item_count: 9,
    resolved_count: 6,
  },
];

const SAMPLE_ITEMS = {
  pl_draft_nordic: [
    { raw_text: 'The Girl with the Dragon Tattoo (2009)', thing_id: 'thing_dragon09', resolution_status: 'resolved', note: null, title: 'The Girl with the Dragon Tattoo', type: 'Movie', year: 2009 },
    { raw_text: 'Insomnia (1997)', thing_id: 'thing_insomnia97', resolution_status: 'resolved', note: null, title: 'Insomnia', type: 'Movie', year: 1997 },
    { raw_text: 'Let the Right One In', thing_id: 'thing_lettheright', resolution_status: 'resolved', note: null, title: 'Let the Right One In', type: 'Movie', year: 2008 },
    { raw_text: 'Jar City', thing_id: null, resolution_status: 'ambiguous', note: 'Two editions, unclear which cut', title: null, type: null, year: null },
    { raw_text: 'The Hunt', thing_id: null, resolution_status: 'unresolved', note: null, title: null, type: null, year: null },
  ],
  pl_provisioned_tv: [
    { raw_text: 'Slow Horses', thing_id: 'thing_slowhorses', resolution_status: 'resolved', note: null, title: 'Slow Horses', type: 'TVSeries', year: 2022 },
    { raw_text: 'The Bureau', thing_id: 'thing_bureau', resolution_status: 'resolved', note: null, title: 'The Bureau', type: 'TVSeries', year: 2015 },
  ],
};

const SAMPLE_EVENTS = {
  pl_draft_nordic: [
    { event_type: 'created', detail: 'Draft created from source page', actor: 'staff@listgem.com', created_at: '2026-08-04T09:12:00Z' },
    { event_type: 'items_replaced', detail: '24 items · 21 resolved', actor: 'staff@listgem.com', created_at: '2026-08-08T15:40:00Z' },
  ],
  pl_provisioned_tv: [
    { event_type: 'created', detail: 'Draft created', actor: 'gtm@listgem.com', created_at: '2026-07-28T13:45:00Z' },
    { event_type: 'status', detail: 'draft → pitched', actor: 'gtm@listgem.com', created_at: '2026-07-30T09:00:00Z' },
    { event_type: 'tokens_issued', detail: 'invite + preview issued, 30d TTL', actor: 'gtm@listgem.com', created_at: '2026-08-08T12:05:00Z' },
    { event_type: 'status', detail: 'pitched → accepted', actor: 'gtm@listgem.com', created_at: '2026-08-08T12:00:00Z' },
    { event_type: 'claimed', detail: 'Invite claimed, list provisioned (list_84c1)', actor: 'system', created_at: '2026-08-10T08:14:00Z' },
  ],
};

export function mockPitchDetail(pitchId) {
  const pitch = MOCK_PITCHES.find(p => p.pitch_id === pitchId);
  if (!pitch) return null;
  return {
    pitch,
    items: SAMPLE_ITEMS[pitchId] || [],
    events: SAMPLE_EVENTS[pitchId] || [
      { event_type: 'created', detail: 'Draft created', actor: pitch.created_by, created_at: pitch.created_at },
    ],
  };
}
